### ISSUE TITLE
Tab toggler

### ISSUE THREAD

**Issue by ifedayoagboola** [ifedayoagboola/bitshub-frontend#93]
Toggle between "Product Info, Question & answer and Review".
See sample:
<img width="1440" alt="Screenshot 2023-01-24 at 09 10 37" src="https://user-images.githubusercontent.com/46829673/214241767-e9125c38-e1ce-459d-92c0-59106b2dcfc0.png">

**Comment by Tobbiloba** [comment]
I'd work on this
